app/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home
    url(
        r'^$',
        'app.views.home',
        name='home',
    ),

    # Home
    url(
        r'^request_provider$',
        'landing.views.landing',
        name='landing',
    ),

    url(
        r'^LiguAdmin/',
        include(admin.site.urls)
    ),

    url(
        r'^accounts/',
        include('userprofile.backends.default.urls')
    ),

    # TinyMCE
    url(r'^tinymce/',
        include('tinymce.urls')
    ),

    # Social auth
    url(
        r'^accounts/',
        include('social_auth.urls'),
    ),

    url(
        r'^accounts/',
        include('userprofile.urls', namespace='userprofile')
    ),

    url(
        r'^cart/',
        include('cart.urls', namespace='cart')
    ),

    url(
        r'^',
        include('store.urls', namespace='store')
    ),
)

# Static content for development
urlpatterns += staticfiles_urlpatterns()

# Serve media for development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns(
    'store.views',

    # Create store
    url(
        r'^store_create/$',
        'store_create',
        name='store-create',
    ),

    # Store detail
    url(
        r'^(?P<slug>[-\w]+)/$',
        'store_detail',
        name='store-detail',
    ),

    # Update store
    url(
        r'^(?P<slug>[-\w]+)/edit/$',
        'store_update',
        name='store-update',
    ),

    # Update store image
    url(
        r'^image_store/(?P<slug>[-\w]+)/$',
        'upload_store_image',
        name='upload-store-image',
    ),

    # Create product
    url(
        r'^(?P<slug>[-\w]+)/product/create/$',
        'product_create',
        name='product-create',
    ),

    # Update product
    url(
        r'^(?P<slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/edit/$',
        'product_update',
        name='product-update',
    ),

    # Update product image
    url(
        r'^image_product/(?P<slug>[-\w]+)/$',
        'upload_product_image',
        name='upload-product-image',
    ),

    # Product detail
    url(
        r'^(?P<slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/$',
        'product_detail',
        name='product-detail',
    ),

    # Products by category
    url(
        r'^category/(?P<category>[-\w]+)/$',
        'products_by_category',
        name='products_by_category',
    ),

    # Delete a product
    url(
        r'^(?P<slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/delete/$',
        'delete_product',
        name='delete_product',
    ),

    # Search tags
    url(
        r'^search/tags/$',
        'ajax_search_tags',
        name='ajax_search_tags',
    ),
)

userprofile/backends/default/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from userprofile.backends.default.views import ActivationView
from userprofile.backends.default.views import RegistrationView


urlpatterns = patterns('',
    url(
        r'^activate/complete/$',
        TemplateView.as_view(template_name='registration/activation_complete.html'),
        name='registration_activation_complete'
    ),

    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(
        r'^activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(),
        name='registration_activate'
    ),

    url(
        r'^register/$',
        RegistrationView.as_view(),
        name='registration_register'
    ),

    url(
        r'^register/complete/$',
        TemplateView.as_view(template_name='registration/registration_complete.html'),
        name='registration_complete'
    ),

    url(r'^register/closed/$',
       TemplateView.as_view(template_name='registration/registration_closed.html'),
       name='registration_disallowed'
    ),

    (r'', include('registration.auth_urls')),
)

userprofile/backends/simple/urls.py
"""
URLconf for registration and activation, using django-registration's
one-step backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.simple.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.views.generic.base import TemplateView

from registration.backends.simple.views import RegistrationView


urlpatterns = patterns('',
                       url(r'^register/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
                       )

userprofile/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns(
    'userprofile.views',

    # login
    url(
        r'^ajax-login/$',
        'ajax_login',
        name='ajax_login',
    ),

    # Ajax register
    url(
        r'^ajax-register/$',
        'ajax_register',
        name='ajax_register',
    ),

    # Ajax register
    url(
        r'^ajax-provider-request/$',
        'ajax_provider_request',
        name='ajax_provider_request',
    ),

    # dashboard
    url(
        r'^dashboard/$',
        'dashboard',
        name='dashboard',
    ),
)

userprofile/backends/default/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import re

from uuid import uuid4

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.sites.models import RequestSite
from django.contrib.sites.models import Site

from userprofile.models import UserProfile
from userprofile.forms import UserRegistrationForm

from registration import signals
from registration.models import RegistrationProfile
from registration.views import ActivationView as BaseActivationView
from registration.views import RegistrationView as BaseRegistrationView

def generate_unique_username(username):
    """Generates unique username. Based on work done by django-social-auth
    """
    maxlen = 22
    uuid_length = 8
    clean_username_regex = re.compile(r'[^\w.@+-_]+')

    initial_username = clean_username_regex.sub('', u'{0}'.format(username))
    username = initial_username[:maxlen + uuid_length]

    while User.objects.filter(username=username).count() > 0:
        username = initial_username[:maxlen] + uuid4().get_hex()[:uuid_length]

    return username


class RegistrationView(BaseRegistrationView):
    """
    The backend for django registration.    
    """
    def register(self, request, **cleaned_data):
        username =  generate_unique_username('{0}.{1}'.format(cleaned_data['name'], cleaned_data['lastname']))
        name, lastname = cleaned_data['name'], cleaned_data['lastname']
        email, password = cleaned_data['email'], cleaned_data['password1']

        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)

        new_user = RegistrationProfile.objects.create_inactive_user(
            username,
            email,
            password,
            site,
        )
        new_user.first_name = name
        new_user.last_name = lastname
        new_user.save()

        UserProfile.objects.create(
            user=new_user
        ).save()

        signals.user_registered.send(
            sender=self.__class__,
            user=new_user,
            request=request,
        )

        return new_user

    def get_form_class(self, request):
        """Return the form to show at registration page
        """
        return UserRegistrationForm

    def registration_allowed(self, request):
        """
        Indicate whether account registration is currently permitted,
        based on the value of the setting ``REGISTRATION_OPEN``. This
        is determined as follows:

        * If ``REGISTRATION_OPEN`` is not specified in settings, or is
          set to ``True``, registration is permitted.

        * If ``REGISTRATION_OPEN`` is both specified and set to
          ``False``, registration is not permitted.
        
        """
        return getattr(settings, 'REGISTRATION_OPEN', True)

    def get_success_url(self, request, user):
        """
        Return the name of the URL to redirect to after successful
        user registration.
        
        """
        return ('registration_complete', (), {})


class ActivationView(BaseActivationView):
    def activate(self, request, activation_key):
        """
        Given an an activation key, look up and activate the user
        account corresponding to that key (if possible).

        After successful activation, the signal
        ``registration.signals.user_activated`` will be sent, with the
        newly activated ``User`` as the keyword argument ``user`` and
        the class of this backend as the sender.
        
        """
        activated_user = RegistrationProfile.objects.activate_user(activation_key)
        if activated_user:
            signals.user_activated.send(sender=self.__class__,
                                        user=activated_user,
                                        request=request)
        return activated_user

    def get_success_url(self, request, user):
        return ('registration_activation_complete', (), {})

def login_on_activation(user, request, **kwargs):
    """Log the user in after link activation
    """
    user.backend = 'django.contrib.auth.backends.ModelBackend'
    login(request, user)

signals.user_activated.connect(login_on_activation)

userprofile/backends/simple/views.py
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.models import User

from registration import signals
from registration.views import RegistrationView as BaseRegistrationView


class RegistrationView(BaseRegistrationView):
    """
    A registration backend which implements the simplest possible
    workflow: a user supplies a username, email address and password
    (the bare minimum for a useful account), and is immediately signed
    up and logged in).
    
    """
    def register(self, request, **cleaned_data):
        username, email, password = cleaned_data['username'], cleaned_data['email'], cleaned_data['password1']
        User.objects.create_user(username, email, password)

        new_user = authenticate(username=username, password=password)
        login(request, new_user)
        signals.user_registered.send(sender=self.__class__,
                                     user=new_user,
                                     request=request)
        return new_user

    def registration_allowed(self, request):
        """
        Indicate whether account registration is currently permitted,
        based on the value of the setting ``REGISTRATION_OPEN``. This
        is determined as follows:

        * If ``REGISTRATION_OPEN`` is not specified in settings, or is
          set to ``True``, registration is permitted.

        * If ``REGISTRATION_OPEN`` is both specified and set to
          ``False``, registration is not permitted.
        
        """
        return getattr(settings, 'REGISTRATION_OPEN', True)

    def get_success_url(self, request, user):
        return (user.get_absolute_url(), (), {})

userprofile/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf import settings
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordResetForm
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.template.loader import render_to_string


from store.models import Store
from store.models import Product
from userprofile.models import ProviderRequest
from userprofile.forms import UserRegistrationForm
from userprofile.forms import ProviderRequestForm


def ajax_login(request):
    """Logs in a user via ajax.
    """
    if request.is_ajax():
        if request.user.is_authenticated():
            return HttpResponse('Usted ya está autenticado.')

        elif request.method == 'POST':
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                login(request, form.get_user())

                return HttpResponse('ok')

        else:
            form = AuthenticationForm()

        return render(request, 'registration/ajax_login.html', {
            'form': form,
        })

    raise Http404


def ajax_register(request):
    """Show the registration form via ajax
    """
    if request.is_ajax():
        form = UserRegistrationForm()

        return render(request, 'registration/ajax_registration_form.html', {
            'form': form,
        })

    raise Http404


def ajax_provider_request(request):
    """This view create a new provider request.
    """
    if request.is_ajax():
        if request.method == 'POST':
            form = ProviderRequestForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                email = form.cleaned_data['email']
                product = form.cleaned_data['product']
                phone = form.cleaned_data['phone']
                more_info = form.cleaned_data['more_info']
                provider_request = ProviderRequest.objects.create(
                    name=name,
                    email=email,
                    product=product,
                    phone=phone,
                    more_info=more_info,
                )

                provider_request.save()

                email_message = EmailMessage(
                    u'[Ligu] Hemos recibido su solicitud en Ligu.',
                    'Para nosotros es muy importante tenerlo en cuenta \
                    \ncomo uno de nuestros proveedores en Ligu, por este \
                    \npor este motivo uno de nuestros asesores estará \
                    \ncontactandose contigo lo más pronto posible.',
                    to=[provider_request.email],
                    headers={'Reply-To': settings.EMAIL_REPLY_TO},
                )
                email_message.content_subtype = 'html'
                email_message.send()

                send_mail(
                    u'[Ligu] Alguien quiere ser proveedor en Ligu!.',
                    u'Una persona esta interesada en ser proveedoraa de Ligu \
                    \nLos datos de la persona son: \
                    \nNombre = {0} \
                    \nCorreo = {1} \
                    \nProducto que ofrece = {2} \
                    \nTelefono de contacto = {3} \
                    \nMas informacion proporcionada por la persona = {4}'.format(
                        provider_request.name,
                        provider_request.email,
                        provider_request.product,
                        provider_request.phone,
                        provider_request.more_info,
                    ),
                    'no-responder@ligu.co',
                    settings.EMAIL_REPLY_TO,
                )
                return HttpResponse('ok')

        else:
            form = ProviderRequestForm()

        return render(request, 'userprofile/ajax_provider_request.html', {
            'form': form,
        })

    raise Http404


@login_required
def dashboard(request):
    """This view show process the list store
    """
    try:
        store = Store.objects.get(created_by=request.user)
    except ObjectDoesNotExist:
        store = False
    products_list = Product.objects.filter(store=store).exclude(quantity__lte=0)
    return render(request, 'userprofile/dashboard.html', {
        'store': store,
        'products_list': products_list,
        'slug': store,
    })

userprofile/templates/userprofile/ajax_provider_request.html
{% load crispy_forms_tags %}

<div class="provider_request_form">
{% if form %}
<form action="{% url 'userprofile:ajax_provider_request' %}" method="post">
    {% crispy form %}
</form>
</div>
{% endif %}

<script>
$(function() {
    'use strict';

    $('.provider_request_form form').on('submit', function () {
        if ($(this).valid()) {
            $.colorbox({html: '<p style="text-align: center; color: #000000;">Gracias por aplicar como proveedor.</p><p style="text-align: center; color: #000000;">Pronto uno de nuestros asesores te contactará. :)</p>', width: '300px', height: '190px', fadeOut: 1000});
            $.post(this.action, $(this).serialize(), function (response) {
                $('.provider_request_form').parent().html(response);
            });
        }

        return false;
    }).validate({
        rules: {
            name: {
                required: true,
            },
            email: {
                required: true,
            },
            product: {
                required: true,
            },
            phone: {
                required: true,
            },
            more_info: {
                required: true,
            },
        }
    });
});
</script>

userprofile/templates/userprofile/dashboard.html
{% extends 'layout/base.html' %}
{% load thumbnail %}

{% block main_content %}
<ul class="breadcrumb">
    <li><a href="{% url 'home' %}">Home</a> <span class="divider">/</span></li>
    <li class="active">Dashboard</li>
</ul>
{% if user.is_authenticated %}
{% if user.userprofile.is_provider %}
{% if store %}
<div class="row">

<div class="span9 post">
<h2 class="page-header"><span>Productos ofrecidos por {{ store.name }}</span></h2>
<div class="sidebar-line"><span></span></div>                        
<div class="row-fluid">
{% if products_list %}
{% for product in products_list %}
{% if forloop.counter0|divisibleby:"4" %}

        {% if forloop.counter0 != 0 %}
        </div>
        <div class="row-fluid">
        {% endif %}

{% endif %}
    <div class="span3">
        <div class="wdt-product">
            <div class="wdt-products-wrapper">
                <div class="wdt-product active show">
                    <a href="{{ product.get_absolute_url }}" title="{{ product.name }}">
                        <img src="{{ product.image|thumbnail_url:'avatar_169' }}" alt="{{ product.name }}" />
                    </a>
                    <h4><a href="{{ product.get_absolute_url }}" title="{{ product.name }}">{{ product.name }}</a></h4>
                    <div class="wdt-pricing">
                        <span class="amount">${{ product.price }}</span>
                    </div>
                    <div class="wdt-cart">
                        <div class="wdt-cart-bar">
                            <a id="add_to_cart" title="Añadir a carrito" data-code="{{ product.id }}" data-price="{{ product.price }}"><i class="icon-shopping-cart"></i><span> Añadir a carrito</span></a>
                        </div>
                    </div>
                    <div class="wdt-overlay">
                        <span class="amount"><a href="{{ product.get_absolute_url }}" title="{{ product.name }}">Ver producto</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if forloop.last %}
    </div>
{% endif %}
{% endfor %}
{% else %}
    Aún no has agregado productos.
</div>
{% endif %} 
</div><!-- end post span -->


<div class="span3 sidebar">
<div class="widget">
<h2 class="widget-title"><span>{{ store.name }}</span></h2>
<div class="sidebar-line"><span></span></div>
<img src="{{ store.logo|thumbnail_url:'avatar_140' }}" alt="{{ store.name }}" />
    <br>
    {{ store.description }}
    <br>
    {{ store.phone }}
    <br>
    {{ store.address }}
{% if user.is_authenticated %}
{% if user.userprofile.is_provider %}
{% if store.created_by == user %}
<p>
<a href="{% url 'store:store-update' store.slug %}" class="btn btn-primary">Actualizar informacion de tienda</a>
<a href="{% url 'store:product-create' store.slug %}" class="btn btn-primary">Agregar nuevo producto</a>
</p>
{% endif %}
{% endif %}
{% endif %}
</div>
</div>
</div>
{% else %}
<p>
	<a class="btn btn-general" href="{% url 'store:store-create' %}">Agregar tienda</a>
</p>
{% endif %}
{% else %}
<p><a class='cbox_provider_request btn btn-general' href="{% url 'userprofile:ajax_provider_request' %}">Aplicar como proveedor.</a></p>
{% endif %}
{% endif %}
{% endblock main_content %}
{% block js %}
<script type="text/javascript">
// Open the provider request colorbox
$('.cbox_provider_request').colorbox();
</script>
{% endblock js %}