app/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home
    url(
        r'^$',
        'app.views.home',
        name='home',
    ),

    # Home
    url(
        r'^request_provider$',
        'landing.views.landing',
        name='landing',
    ),

    url(
        r'^LiguAdmin/',
        include(admin.site.urls)
    ),

    url(
        r'^accounts/',
        include('userprofile.backends.default.urls')
    ),

    # TinyMCE
    url(r'^tinymce/',
        include('tinymce.urls')
    ),

    # Social auth
    url(
        r'^accounts/',
        include('social_auth.urls'),
    ),

    url(
        r'^accounts/',
        include('userprofile.urls', namespace='userprofile')
    ),

    url(
        r'^cart/',
        include('cart.urls', namespace='cart')
    ),

    url(
        r'^',
        include('store.urls', namespace='store')
    ),
)

# Static content for development
urlpatterns += staticfiles_urlpatterns()

# Serve media for development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns(
    'cart.views',

    # Cart list
    url(
        r'^$',
        'cart_detail',
        name='cart_detail',
    ),

    # Cart complete order
    url(
        r'^complete/$',
        'cart_complete',
        name='cart_complete',
    ),
)

userprofile/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns(
    'userprofile.views',

    # login
    url(
        r'^ajax-login/$',
        'ajax_login',
        name='ajax_login',
    ),

    # Ajax register
    url(
        r'^ajax-register/$',
        'ajax_register',
        name='ajax_register',
    ),

    # Ajax register
    url(
        r'^ajax-provider-request/$',
        'ajax_provider_request',
        name='ajax_provider_request',
    ),

    # dashboard
    url(
        r'^dashboard/$',
        'dashboard',
        name='dashboard',
    ),
)

app/templates/layout/base.html
{% load googletools staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	{% site_verification_code %}

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    
	<!-- Set meta informations -->
	<title>Ligu - {% block title %}{% endblock title %}</title>
	<meta name="description" content="The Bistro is a responsive ecommerce template for your next projects">
	<meta name="author" content="">
    
	<!-- Style Files -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,700italic,800" rel="stylesheet" type="text/css">  
	<link rel="stylesheet" href="{% static 'layerslider/css/layerslider.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/media.css' %}">
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/colorbox.css' %}">
  <link rel="stylesheet" href="{% static 'css/colorbox.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.tagit.css' %}">
  <link rel="stylesheet" href="{% static 'css/tagit.ui-zendesk.css' %}">

	<!--[if IE 7]>
		<link rel="stylesheet" href="{% static 'css/font-awesome-ie7.min.css' %}">
	<![endif]-->  

	<!-- JS Files -->
	<script>
		document.documentElement.className = document.documentElement.className.replace(/(\s|^)no-js(\s|$)/, '$1js$2');
	</script>
    
     <!--[if lt IE 9]>
		<script src="{% static 'js/html5shiv.min.js' %}"></script>
	<![endif]--> 
{% analytics_code %}
    
</head>
<body>

	<!-- Start Top Bar -->
    <div class="container tophead">
    	<div class="left span3">
        	<ul class="social">
            	<li><a title="Like us on Facebook" data-placement="bottom" data-toggle="tooltip" href="#"><i class="icon-facebook"></i></a></li>
            	<li><a title="Follow us on Twitter" data-placement="bottom" data-toggle="tooltip" href="#"><i class="icon-twitter"></i></a></li>
            	<li><a title="Circle us on Google Plus" data-placement="bottom" data-toggle="tooltip" href="#"><i class="icon-google-plus"></i></a></li>
            	<li><a title="Follow us on Linkedin" data-placement="bottom" data-toggle="tooltip" href="#"><i class="icon-linkedin"></i></a></li>
            	<li><a title="Be friend on Xing" data-placement="bottom" data-toggle="tooltip" href="#"><i class="icon-xing"></i></a></li>
            	<li><a title="Pin it on Pinterest" data-placement="bottom" data-toggle="tooltip" href="#"><i class="icon-pinterest"></i></a></li>
            </ul>
        </div>
        <div class="right">
                <div id="wdt-links">
                    <ul>
                        <li class="dropdown hover cart"><a href="{% url 'cart:cart_detail' %}"><i class="icon-shopping-cart"></i> Your Cart <span class="label label-success font14"><span id="cart_count">0</span> item(s)</span> - $<span id="cart_cash"></span> <i class="icon-arrow-down"></i></a>
                        </li>
                        {% if user.is_authenticated %}
                        {% else %}
                        <li class="register"><a href="{% url 'userprofile:ajax_register' %}" id="wdt-register" class="cbox_register">Register <i class="icon-user"></i></a></li>
                        <li><a href="{% url 'userprofile:ajax_login' %}" id="id_take_button" class="cbox_login" >Login <i class="icon-unlock-alt"></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
	<!-- END Top Bar -->

    <!-- Start Header Bar -->
    <div class="container header-wrap make-bg">
		<div class="left brand">
           <h1><a href="{% url 'home' %}">Ligu</a></h1>
        </div>
        <div class="right">
        	<div class="searchbar span3">
                <form class="form-search">
              <input type="text" placeholder="Search" data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska"]'>
                </form>
		    </div>
		</div>
	</div>
        
	<div class="container make-bg">
		<div class="navbar">
			<div class="container">
				<div class="navbar-inner">
					<button class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  	<span class="icon-bar"></span>
                  	<span class="icon-bar"></span>
                  	<span class="icon-bar"></span>
                	</button>
                	<div class="nav-collapse collapse">
			<ul class="nav pull-left">
				<li class="active"><a href="{% url 'home' %}">Home</a></li>
        <li><a href="http://ligu.co/blog">Blog</a></li>
				{# <li class="dropdown dropdown-hover"> #}
                  {# <a class="dropdown-toggle" href="#" data-toggle="dropdown">Categorias <span class="caret"></span></a> #}
                      {# <div class="dropdown-menu span4"> #}
                        {# <div class="row"> #}
                          {# <div class="span2"> #}
                            {# <ul class="mega-menu-links"> #}
                              {# <li><a href="category-list.html">Cupcakes</a></li> #}
                              {# <li><a href="category-list.html">Joyas</a></li> #}
                              {# <li><a href="category-list.html">Restaurantes</a></li> #}
                              {# <li><a href="category-list.html">Cenas romanticas</a></li> #}
                            {# </ul> #}
                          {# </div> #}
                          {# <div class="span2"> #}
                            {# <ul class="mega-menu-links"> #}
                              {# <li><a href="category-list.html">Spa's</a></li> #}
                              {# <li><a href="category-list.html">Perfumes</a></li> #}
                              {# <li><a href="category-list.html">Chocolates</a></li> #}
                              {# <li><a href="category-list.html">Flores</a></li> #}
                            {# </ul> #}
                          {# </div> #}
					   {# </div> #}
					{# </div> #}
                {# </li> #}
                       {# <li class="dropdown dropdown-hover"> #}
                          {# <a class="dropdown-toggle" href="#" data-toggle="dropdown">Por personalidad <span class="caret"></span></a> #}
                          {# <div class="dropdown-menu span2"> #}
                            {# <div class="row"> #}
                              {# <div class="span2"> #}
                                {# <ul class="mega-menu-links"> #}
	                              {# <li><a href="category-list.html">Aventurera</a></li> #}
	                              {# <li><a href="category-grid.html">Creativa</a></li> #}
	                              {# <li><a href="category-sidebar.html">Dormilona</a></li> #}
                                  {# <li><a href="daily-deals.html">Friki o Geek</a></li> #}
                                {# </ul> #}
                              {# </div> #}
                            {# </div> #}
                          {# </div> #}
                        {# </li> #}
                      </ul>
                      {% if user.is_authenticated %}
                        <ul class="nav pull-right">
                      <li class="dropdown dropdown-hover">
                          <a class="dropdown-toggle" href="#" data-toggle="dropdown">{{ user.first_name }} {{ user.last_name }} <span class="caret"></span></a>
                          <div class="dropdown-menu span2">
                            <div class="row">
                              <div class="span2">
                                <ul class="mega-menu-links">
                                  {# <li><a href="#">Mis tiendas</a></li> #}
                                  {# <li><a href="#">Mis ventas</a></li> #}
                                  {# <li><a href="#">Mis compras</a></li> #}
                                  <li><a href="{% url 'userprofile:dashboard' %}">Dashboard</a></li>
                                  <li><a href="{% url 'auth_logout' %}">Cerrar sesión</a></li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </li>
                    </ul>
                    {% endif %}
                </div>
				{% block navigation %}
				{% endblock navigation %}
				</div>
			</div>
		</div>
	</div>
	<!-- END Header Bar -->

	<!-- Start Site Container -->
    
    <div class="container make-bg">
    	{% block main_content %}
		{% endblock main_content %}
	</div>
    
	<!-- End Site Container -->
    
    <div class="container">
	<!-- Start Footer -->
		{# <footer class="footer-wrapper"> #}
			{% block footer %}
			{% endblock footer %}
		{# </footer> #}
	<!-- End Footer -->
    
	<!-- Start Copyright -->
	<div class="copyright"> 
		<div class="footer-menu left">
            <ul class="menu">
                <li><a href="{% url 'home' %}">Home</a></li>
            </ul>
        </div>       
        <div class="right">
        	<p>© {% now "Y" %} <a href="{% url 'home' %}">Ligu store</a>. All rights reserved.</p>

        </div>
	</div>
	<!-- End Copyright -->
<div class="wdttop">Scroll To Top</div>
</div>
    
	<!-- JS Files -->
	<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery-easing-1.3.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery-transit-modified.js' %}" type="text/javascript"></script>
	<script src="{% static 'layerslider/js/layerslider.transitions.js' %}" type="text/javascript"></script>
	<script src="{% static 'layerslider/js/layerslider.kreaturamedia.jquery.js' %}" type="text/javascript"></script> 
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.flexslider.min.js' %}"></script>
	<script src="{% static 'js/countdown.js' %}"></script>
	<script src="{% static 'js/jflickrfeed.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/jquery.cookie.js' %}"></script>
	<script src="{% static 'js/jquery.colorbox-min.js' %}"></script>
  <script src="{% static 'js/jquery.validate.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui-1.9.0.min.js' %}"></script>
  <script src="{% static 'js/tag-it.min.js' %}"></script>

	<!-- Flickr JS -->
	<script>
		$(document).ready(function() {
		  $('.flickr').jflickrfeed({
			limit: 8,
			qstrings: {id: '52617155@N08'},
			itemTemplate: '<li><a href="{{link}}"><img src="{{image_s}}" alt="{{title}}" /></a></li>'
		  });
		});
	</script>
	<script src="{% static 'js/main.js' %}"></script>
	{% block js%}
	{% endblock js%}

</body>
</html>